"""Generate PDF invoices using fpdf2."""

import io
import logging
from decimal import Decimal
from typing import Any

from fpdf import FPDF

logger = logging.getLogger(__name__)


def generate_invoice_pdf(
    invoice_number: str,
    student_name: str,
    due_date: str,
    total_amount: str,
    currency: str,
    line_items: list[dict[str, Any]],
    tenant_name: str,
    tenant_address: str | None = None,
    tenant_phone: str | None = None,
    tenant_email: str | None = None,
    banking_details: str | None = None,
    payment_instructions: str | None = None,
) -> bytes:
    """Generate a PDF invoice and return the bytes."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # --- Header: School name ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, tenant_name, new_x="LMARGIN", new_y="NEXT")

    # School contact info
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    if tenant_address:
        for line in tenant_address.strip().splitlines():
            pdf.cell(0, 4.5, line.strip(), new_x="LMARGIN", new_y="NEXT")
    if tenant_phone:
        pdf.cell(0, 4.5, f"Tel: {tenant_phone}", new_x="LMARGIN", new_y="NEXT")
    if tenant_email:
        pdf.cell(0, 4.5, f"Email: {tenant_email}", new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # --- INVOICE title ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "INVOICE", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # --- Invoice details ---
    pdf.set_font("Helvetica", "", 10)
    _detail_row(pdf, "Invoice Number:", invoice_number)
    _detail_row(pdf, "Student:", student_name)
    _detail_row(pdf, "Due Date:", due_date)
    pdf.ln(6)

    # --- Line Items Table ---
    page_w = pdf.w - pdf.l_margin - pdf.r_margin
    col_desc = page_w * 0.50
    col_qty = page_w * 0.12
    col_unit = page_w * 0.19
    col_total = page_w * 0.19

    # Table header
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(col_desc, 8, "Description", border=1, fill=True)
    pdf.cell(col_qty, 8, "Qty", border=1, fill=True, align="C")
    pdf.cell(col_unit, 8, "Unit Price", border=1, fill=True, align="R")
    pdf.cell(col_total, 8, "Total", border=1, fill=True, align="R")
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 9)
    for item in line_items:
        desc = str(item.get("description", ""))
        qty = str(item.get("quantity", 1))
        unit = f"{currency} {_fmt(item.get('unit_amount', 0))}"
        total = f"{currency} {_fmt(item.get('total_amount', 0))}"

        pdf.cell(col_desc, 7, desc, border="LR")
        pdf.cell(col_qty, 7, qty, border="LR", align="C")
        pdf.cell(col_unit, 7, unit, border="LR", align="R")
        pdf.cell(col_total, 7, total, border="LR", align="R")
        pdf.ln()

    # Total row
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col_desc + col_qty + col_unit, 9, "Total Due", border=1, fill=True, align="R")
    pdf.cell(col_total, 9, f"{currency} {total_amount}", border=1, fill=True, align="R")
    pdf.ln(12)

    # --- Banking Details ---
    if banking_details:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Banking Details", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for line in banking_details.strip().splitlines():
            pdf.cell(0, 5, line.strip(), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # --- Payment Instructions ---
    if payment_instructions:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, "Payment Instructions", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for line in payment_instructions.strip().splitlines():
            pdf.cell(0, 5, line.strip(), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # --- Footer ---
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(0, 5, f"Generated by ClassUp on behalf of {tenant_name}", align="C")

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def _detail_row(pdf: FPDF, label: str, value: str) -> None:
    """Render a label: value row."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, label)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")


def _fmt(val: Any) -> str:
    """Format a numeric value to 2 decimal places."""
    try:
        return f"{float(val):.2f}"
    except (TypeError, ValueError):
        return str(val)
