"""Generate a PDF for a DailyReport, using fpdf2.

Rendered from the report's template.sections structure + the JSONB
report_data — same source of truth the web view uses. No headless
browser, no system-package dependencies (fpdf2 is pure Python), so
it works identically on developer laptops and Railway builds.

Section renderers below cover every ReportTemplateSection type in the
schema (per CLAUDE.md):
  CHECKLIST · REPEATABLE_ENTRIES · NARRATIVE · ACADEMIC_GRADES ·
  MEALS · INFO_DISPLAY · SUMMARY · SIGNATURES

Unknown section types render as a plain "field: value" table — a
never-blank fallback so a new template type doesn't break the PDF.
"""

from __future__ import annotations

import logging
from typing import Any

from fpdf import FPDF
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import DailyReport, Tenant

logger = logging.getLogger(__name__)


async def render_report_pdf(
    db: AsyncSession, report: DailyReport,
) -> bytes:
    """Render one report to PDF bytes.

    Loads the tenant name for the header. All other data comes off the
    report's eager-loaded relationships (student, school_class, template)
    plus its ``report_data`` JSONB.
    """
    tenant = None
    if report.tenant_id:
        tenant = await db.get(Tenant, report.tenant_id)

    student_name = "Student"
    if report.student:
        student_name = f"{report.student.first_name} {report.student.last_name}".strip()

    class_name = report.school_class.name if report.school_class else "(no class)"
    tenant_name = tenant.name if tenant else "ClassUp"
    template_name = report.template.name if report.template else "Report"
    report_type = report.template.report_type if report.template else ""

    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # --- Header (tenant + report title) ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, tenant_name, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, template_name, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # --- Student block ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Student:", new_x="RIGHT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, student_name, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Class:", new_x="RIGHT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, class_name, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(35, 6, "Report date:", new_x="RIGHT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, report.report_date.strftime("%A %d %B %Y"), new_x="LMARGIN", new_y="NEXT")
    if report_type:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(35, 6, "Type:", new_x="RIGHT")
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 6, report_type.replace("_", " ").title(), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    _hr(pdf)
    pdf.ln(4)

    # --- Sections ---
    template_sections = (
        report.template.sections if report.template and report.template.sections else []
    )
    report_sections: dict[str, Any] = (
        (report.report_data or {}).get("sections", {}) if report.report_data else {}
    )

    for section in sorted(template_sections, key=lambda s: s.get("display_order", 0)):
        section_id = section.get("id")
        section_type = (section.get("type") or "").upper()
        section_data = report_sections.get(section_id, {}) if section_id else {}
        _render_section_header(pdf, section)

        try:
            renderer = _SECTION_RENDERERS.get(section_type, _render_generic)
            renderer(pdf, section, section_data)
        except Exception:
            # NEVER let a broken section abort the whole PDF. Log,
            # emit a placeholder, keep rendering the rest — parent
            # gets an imperfect PDF instead of no PDF.
            logger.exception(
                "Report section render failed: report=%s section=%s type=%s",
                report.id, section_id, section_type,
            )
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(180, 80, 80)
            pdf.multi_cell(0, 5, "(This section could not be rendered.)")
            pdf.set_text_color(0, 0, 0)

        pdf.ln(4)

    # --- Footer note ---
    pdf.ln(4)
    _hr(pdf)
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    finalized = report.finalized_at.strftime("%d %b %Y %H:%M") if report.finalized_at else "not finalised"
    pdf.cell(0, 4, f"Finalised: {finalized}. Generated by ClassUp.", new_x="LMARGIN", new_y="NEXT")

    output = pdf.output()
    return bytes(output) if isinstance(output, bytearray) else output


class _ReportPDF(FPDF):
    """Small subclass so we can add a running header/footer later if needed
    without changing the render function's shape."""
    pass


def _hr(pdf: FPDF) -> None:
    """Light grey horizontal rule across the page width."""
    pdf.set_draw_color(210, 210, 210)
    x = pdf.get_x()
    y = pdf.get_y()
    w = pdf.w - pdf.l_margin - pdf.r_margin
    pdf.line(x, y, x + w, y)


def _render_section_header(pdf: FPDF, section: dict[str, Any]) -> None:
    title = section.get("title") or "(untitled section)"
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_fill_color(240, 240, 245)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 7, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def _render_kv_row(pdf: FPDF, label: str, value: str) -> None:
    """One label + value row — used across most section types.

    Uses pdf.write() rather than cell + multi_cell. write() flows text
    naturally across the page width without any cursor-drift trap:
    fpdf2's multi_cell(w=0, ...) computes remaining width from the
    current x, and a previous multi_cell's ``new_y="NEXT"`` doesn't
    always reset x to the left margin — leaving the next multi_cell
    with zero remaining space and the exception:
      Not enough horizontal space to render a single character
    write() sidesteps that entirely.
    """
    # Belt-and-braces cursor reset — irrelevant to write() itself but
    # keeps the SECTION HEADER below our text properly aligned.
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 10)
    pdf.write(5.5, f"{label}: ")
    pdf.set_font("Helvetica", "", 10)
    # Truncate absurdly long values so one wonky field can't blow the
    # renderer with a 100KB single string. 2000 chars is well past
    # anything a school-report field should hold.
    val = str(value if value not in (None, "") else "-")[:2000]
    pdf.write(5.5, val)
    pdf.ln(5.5)


def _render_checklist(pdf: FPDF, section: dict, data: dict) -> None:
    for field in section.get("fields") or []:
        label = field.get("label") or field.get("id", "field")
        raw = data.get(field.get("id"))
        val = _fmt_field_value(field, raw)
        _render_kv_row(pdf, label, val)


def _render_narrative(pdf: FPDF, section: dict, data: dict) -> None:
    for field in section.get("fields") or []:
        raw = data.get(field.get("id"))
        val = str(raw or "").strip()[:8000]  # sanity cap on narrative length
        if not val:
            continue
        # Reset cursor to left margin so an earlier section's cursor
        # position can't leave multi_cell with zero remaining width.
        if field.get("label"):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 10)
            pdf.write(5.5, field["label"] + ":")
            pdf.ln(5.5)
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5.5, val)
        pdf.ln(1)


def _render_repeatable(pdf: FPDF, section: dict, data: dict) -> None:
    entries = (data or {}).get("entries") or []
    fields = section.get("fields") or []
    if not entries:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "(No entries recorded.)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        return
    for i, entry in enumerate(entries, start=1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Entry #{i}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        for field in fields:
            label = field.get("label") or field.get("id", "field")
            raw = entry.get(field.get("id"))
            _render_kv_row(pdf, "  " + label, _fmt_field_value(field, raw))
        pdf.ln(1)


def _render_academic_grades(pdf: FPDF, section: dict, data: dict) -> None:
    subjects = section.get("subjects") or []
    grading = section.get("grading_system") or []
    if not subjects:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "(No subjects configured for this section.)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        return
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 245)
    pdf.cell(65, 6, "Subject", border=1, fill=True)
    pdf.cell(25, 6, "Mark", border=1, fill=True, align="C")
    pdf.cell(25, 6, "Grade", border=1, fill=True, align="C")
    pdf.cell(0, 6, "Remarks", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for subject in subjects:
        sid = subject.get("id")
        sname = subject.get("name") or "Subject"
        total = subject.get("total_marks") or 100
        entry = (data or {}).get(sid, {}) if isinstance(data, dict) else {}
        marks = entry.get("marks_obtained")
        remarks = entry.get("remarks") or ""
        try:
            marks_num = float(marks) if marks is not None else None
        except (TypeError, ValueError):
            marks_num = None
        grade = _grade_for(marks_num, total, grading)
        pdf.cell(65, 5.5, str(sname)[:38], border=1)
        pdf.cell(25, 5.5, f"{marks}/{total}" if marks is not None else "-", border=1, align="C")
        pdf.cell(25, 5.5, grade or "-", border=1, align="C")
        pdf.cell(0, 5.5, str(remarks)[:60], border=1, new_x="LMARGIN", new_y="NEXT")


def _render_meals(pdf: FPDF, section: dict, data: dict) -> None:
    for field in section.get("fields") or []:
        label = field.get("label") or field.get("id", "meal")
        raw = data.get(field.get("id"))
        _render_kv_row(pdf, label, _fmt_field_value(field, raw))


def _render_info_display(pdf: FPDF, section: dict, data: dict) -> None:
    _render_checklist(pdf, section, data)


def _render_summary(pdf: FPDF, section: dict, data: dict) -> None:
    _render_checklist(pdf, section, data)


def _render_signatures(pdf: FPDF, section: dict, data: dict) -> None:
    for field in section.get("fields") or []:
        label = field.get("label") or "Signature"
        raw = data.get(field.get("id"))
        val = str(raw or "").strip()
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(60, 5.5, f"{label}:", new_x="RIGHT")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 5.5, val or "_____________________", new_x="LMARGIN", new_y="NEXT")


def _render_generic(pdf: FPDF, section: dict, data: dict) -> None:
    if not data:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, "(No data.)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        return
    for field in section.get("fields") or []:
        label = field.get("label") or field.get("id", "field")
        raw = data.get(field.get("id"))
        _render_kv_row(pdf, label, _fmt_field_value(field, raw))


_SECTION_RENDERERS = {
    "CHECKLIST": _render_checklist,
    "NARRATIVE": _render_narrative,
    "REPEATABLE_ENTRIES": _render_repeatable,
    "ACADEMIC_GRADES": _render_academic_grades,
    "MEALS": _render_meals,
    "INFO_DISPLAY": _render_info_display,
    "SUMMARY": _render_summary,
    "SIGNATURES": _render_signatures,
}


def _fmt_field_value(field: dict, value: Any) -> str:
    """Turn any JSONB field value into a printable string, respecting
    the field's declared type."""
    if value is None or value == "":
        return "-"
    ftype = (field.get("type") or "").upper()
    if ftype == "CHECKBOX":
        return "Yes" if value else "No"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    if isinstance(value, dict):
        return ", ".join(f"{k}: {v}" for k, v in value.items())
    return str(value)


def _grade_for(marks: float | None, total: float | int, grading: list[dict]) -> str:
    """Map a mark against the grading_system bands. Returns "" if the
    mark is missing or no band matches."""
    if marks is None or not grading:
        return ""
    try:
        pct = (marks / float(total)) * 100 if total else 0
    except Exception:
        return ""
    for band in grading:
        try:
            lo = float(band.get("min", 0))
            hi = float(band.get("max", 100))
        except Exception:
            continue
        if lo <= pct <= hi:
            return str(band.get("grade") or "")
    return ""
